# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wtd_polya_sample_cpp <- function(size, wts) {
    .Call('_bestimate_wtd_polya_sample_cpp', PACKAGE = 'bestimate', size, wts)
}

